# fly.toml app configuration file generated for word-stash on 2025-08-27T16:00:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'word-stash'
primary_region = 'iad'
kill_signal = 'SIGTERM'

[build]

[env]
  DATABASE_PATH = '/mnt/name/name.db'
  REPLICA_URL = 's3://word-stash-db-backup/name.db'
  PHX_HOST = 'word-stash.fly.dev'
  PORT = '8080'
  MIX_ENV = 'prod'

[[mounts]]
  source = 'name'
  destination = '/mnt/name'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
