app = "your-app-name"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "4096mb"   # 2GB OK for extractive-only; bump to 4096 for transformers
  cpu_kind = "shared"
  cpus = 2

